- name: Configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: Disable current NodeJS 
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable NodeJS 20 Version
    ansible.builtin.command: dnf module enable nodejs:20 -y
    
  - name: Install NodeJS # IMP POINT ---For installations we need NOt write the commands against the module 
    ansible.builtin.package:
      name: nodejs
      state: present # IMP POINT - Since we used package module we need to give "present. If we have used dnf module then we need to write as "installed"

  - name: create expense user
    ansible.builtin.user:
      name: expense

  - name: create app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes # this is required as our source is in our backend server but NOT in ansible server

  - name: Install nodejs dependencies i.e. npm
    community.general.npm:
      path: /app # Inside app folder when we unzipped our code we get package.json file & at this place we need to install npm
      # thats why path we are giving as /app for installing npm

  - name: copy backend service from ansible server to backend server
    ansible.builtin.copy:
      src: backend.service 
      dest: /etc/systemd/system/backend.service # Here we are even mentioning backend.server at the end becoz 
      #contents of the backend.service will be directly copied to folder created by us 
      # by name (backend.service) to destination location of backend server inside the backend.service folder directly

